
example.so:	example.cpp VamPipeAdapter.h VamPipePluginLibrary.h VamPipePluginLibrary.cpp
		c++ -std=c++11 -fPIC \
		-I../vamp-plugin-sdk -I.. -I../json \
		-Wall -Wextra -g \
		-shared -Wl,-Bsymbolic -Wl,-soname=example.so -Wl,-z,defs -Wl,--version-script=vampipe.map \
		example.cpp \
		VamPipePluginLibrary.cpp \
		../vamp-plugin-sdk/examples/ZeroCrossing.cpp \
		../vamp-plugin-sdk/examples/SpectralCentroid.cpp \
		../vamp-plugin-sdk/examples/PercussionOnsetDetector.cpp \
		../vamp-plugin-sdk/examples/FixedTempoEstimator.cpp \
		../vamp-plugin-sdk/examples/AmplitudeFollower.cpp \
		../vamp-plugin-sdk/examples/PowerSpectrum.cpp \
		../json/json11/json11.cpp \
		../vamp-plugin-sdk/libvamp-hostsdk.a \
		../vamp-plugin-sdk/libvamp-sdk.a \
		-o example.so

