
PIPER_VAMP_JS_DIR	:= ../..
PLUGIN_SRC_DIR		:= ../../../vamp-test-plugin

MODULE_NAME		:= VampTestPlugin
MODULE_SOURCE		:= vamp-test-plugin.cpp

PLUGIN_SOURCES		:= $(PLUGIN_SRC_DIR)/VampTestPlugin.cpp
INCLUDES		:= -I$(PLUGIN_SRC_DIR)

include $(PIPER_VAMP_JS_DIR)/Makefile.inc
